/**
 * @file[zh-cn] encodings_pars_fragment  ShaderChunk GLSL 片段
 * @brief[zh-cn] ShaderChunk GLSL 片段: encodings_pars_fragment
 *
 * @file[en] encodings_pars_fragment  ShaderChunk GLSL fragment
 * @brief[en] ShaderChunk GLSL fragment: encodings_pars_fragment
 */
package three.rendering.shaders.ShaderChunk

/**
 * encodings_pars_fragment GLSL 片段字符串
 */
public const encodings_pars_fragment: String = #"
// encodings not implemented
"#
